title: The Mercury

subscriptions:
    - title: 依云's Blog
      url  : http://blog.lilydjwg.me/feed
      site : http://blog.lilydjwg.me/
    - title: 云风的博客
      url  : http://blog.codingnow.com/atom.xml
      site : http://blog.codingnow.com/
    - title: Beyond the Void
      url  : https://www.byvoid.com/feed
      site : https://www.byvoid.com/
    - title: Blahgeek's Blog
      url  : https://blog.blahgeek.com/feeds/all.rss.xml
      site : https://blog.blahgeek.com/
    - title: Capbone
      url  : http://capbone.com/feed/
      site : http://capbone.com/
    - title: Yuxin's Blog
      url  : http://ppwwyyxx.com/atom.xml
      site : http://ppwwyyxx.com/
    - title: 吴非
      url  : http://blog.sina.com.cn/rss/1916167487.xml
      site : http://blog.sina.com.cn/wufei2011
    - title: McFlog
      url  : http://mcfloundinho.tk/feeds/all.rss.xml
      site : http://mcfloundinho.tk/
    - title: delphij's chaos
      url  : https://blog.delphij.net/atom.xml
      site : https://blog.delphij.net/
    - title: FreeBSD News Flash
      url  : https://www.freebsd.org/news/rss.xml
      site : https://www.freebsd.org/news/
    - title: FiveYellowMice
      url  : https://fiveyellowmice.com/feed.xml
      site : https://fiveyellowmice.com/
    - title: Phoenix's island
      url  : https://blog.phoenixlzx.com/atom.xml
      site : https://blog.phoenixlzx.com/
    - title: 阮一峰的博客
      url  : http://www.ruanyifeng.com/blog/atom.xml
      site : http://www.ruanyifeng.com/
    - title: 木遥的窗子
      url  : http://blog.farmostwood.net/feed
      site : http://blog.farmostwood.net/