title: The Mercury

subscriptions:
    - title: Solidot
      url  : http://www.solidot.org/index.rss
      site : http://www.solidot.org/
    - title: FiveYellowMice
      url  : https://fiveyellowmice.com/feed.xml
      site : https://fiveyellowmice.com/
    - title: 依云's Blog
      url  : http://blog.lilydjwg.me/feed
      site : http://blog.lilydjwg.me/
    - title: 云风的博客
      url  : http://blog.codingnow.com/atom.xml
      site : http://blog.codingnow.com/
    - title: Beyong the Void
      url  : https://www.byvoid.com/feed
      site : https://www.byvoid.com/
    - title: Blahgeek's Blog
      url  : https://blog.blahgeek.com/feeds/all.rss.xml
      site : https://blog.blahgeek.com/
    - title: Capbone
      url  : http://capbone.com/feed/
      site : http://capbone.com/
    - title: Yuxin's Blog
      url  : http://ppwwyyxx.com/atom.xml
      site : http://ppwwyyxx.com/